### PR TITLE
Fixes to HDFS Ansible playbook for SystemD systems.

### PR DESCRIPTION
**Pull request by teralype**

### CODE REVIEW

**Comment by chicofranchico** [comment]
how did you run the playbook? I think if the `is defined` is required since the hostname is an optional value and might complain if it's not set

**Comment by teralype** [comment]
@chicofranchico the `is defined` is not for the hostname but the domain name, `hdfs_host_domain_name` which AFAICS is always defined for all of our clusters (except T01) because they use non-qualified domain names.

**Comment by calmacara** [comment]
I agree, `is defined` is mandatory because it's also used elsewhere in the role. The README says ```* `hdfs_host_domain_name`: Only set this variable if your host entries are not FQDNs. E.g. value: "node.dns.example.com"```

**Comment by teralype** [comment]
@chicofranchico and @calmacara ok, let me figure out something that works for T01 because in T01 all the hosts are FQDNs and because of this, generated HDFS configuration is incorrect with the hostname and the DNS suffix appended twice.

**Comment by teralype** [comment]
PTAL

**Pull request merged**
